### ISSUE TITLE
Cannot paste feed URL on Android

### ISSUE THREAD

**Issue by astro** [sebastiansIT/HTML5Podcatcher#1]
Dumme Frage: Wie paste ich eine Feed-URL aus dem Clipboard mit Firefox auf Android? Das übliche Popup bei Longpress bleibt aus.

Firefox 43.0
Android 6.0.1

**Comment by sebastiansIT** [comment]
Hi Astro,

ich versteh GitHub offensichtlich nicht: Hätte gedacht das ich über eine Issue eine Mailbenachrichtigung bekomme. Ist aber nicht so. Daher die 'etwas' verspätete Antwort.

Wenn du den Podcatcher über den Firefox Marketplace installiert hattest (was mittlerweile auf Android nicht mehr geht) konntest du tatsächlich die Zwischenablage nicht nutzen, da blieb nur manuelles Eintippen übrig.
